services:
  it-tools:
    container_name: it-tools
    restart: always
    # ports:
    #   - 80
    image: corentinth/it-tools:latest

    networks:
      - proxy

networks:
  proxy:
    external: true
