services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    container_name: n8n
    # ports:
    #   - "5678:5678"
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - GENERIC_TIMEZONE=Asia/Phnom_Penh
      - TZ=Asia/Phnom_Penh
    networks:
      - proxy
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n-local-files:/files

volumes:
  n8n_data:

networks:
  proxy:
    external: true
